import * as express from 'express';
import * as bodyBarser from 'body-parser';
import * as cors from 'cors';

// import all controllers before routes registration
import '@js-machine-app/api/controllers';

// routes are auto-generated by tsoa
import { RegisterRoutes } from '@js-machine-app/api/routes';

const app = express();

app
  .use(cors({ origin: true }) as string)
  .use(bodyBarser.json())
  .use(bodyBarser.urlencoded({ extended: false }));

RegisterRoutes(app);

app.get('*', (_, res) =>
  res.status(404).json({
    success: false,
    data: 'Endpoint not found',
  }),
);

export default app;
