# Generated by Django 2.2.2 on 2019-07-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190718_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='Base user test', max_length=255),
            preserve_default=False,
        ),
    ]
