# Generated by Django 2.2.2 on 2019-07-18 13:18

from django.db import migrations, models
import django.utils.timezone
import js_machine.users.validations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190718_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now, validators=[js_machine.users.validations.validate_birthday]),
            preserve_default=False,
        ),
    ]
