version: '3'

volumes:
  pgdata: {}

services:
  web:
    build:
      context: .
      dockerfile: ./docker/local/web/Dockerfile
    image: js_machine_local_web
    depends_on:
      - postgres
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
    command: /start

  postgres:
    image: "postgres:10.5"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
