trigger:
  branches:
    exclude:
      - master

pr:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    displayName: 'Install Node.js'
    inputs:
      versionSpec: '10.x'

  - script: |
      npm ci
      npm run test
      npm run build
    displayName: 'Install, test and build'
    workingDirectory: './js_machine_front'
